SELECT  YEAR(S.SALES_DATE) AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT I.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT I.USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM USER_INFO I
    LEFT JOIN ONLINE_SALE S
    ON I.USER_ID = S.USER_ID
WHERE YEAR(I.JOINED) = 2021
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
HAVING YEAR IS NOT NULL
ORDER BY YEAR ASC, MONTH ASC