SELECT CAR.CAR_ID, CAR.CAR_TYPE, TRUNCATE(CAR.DAILY_FEE * (100 - PLN.DISCOUNT_RATE) * 0.01 * 30, 0) AS 'FEE'
FROM CAR_RENTAL_COMPANY_CAR CAR
         JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
              ON CAR.CAR_ID = HIS.CAR_ID
         JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLN
              ON CAR.CAR_TYPE = PLN.CAR_TYPE
WHERE CAR.CAR_ID NOT IN(SELECT HIS.CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
                        WHERE HIS.START_DATE < '2022-12-01' AND HIS.END_DATE > '2022-11-01')
  AND CAR.CAR_TYPE IN('세단', 'SUV')
  AND PLN.DURATION_TYPE = '30일 이상'
GROUP BY CAR.CAR_ID
HAVING FEE BETWEEN 500000 AND 2000000 - 1
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC